### ISSUE TITLE
Assistant Judge Database Error

### ISSUE THREAD

**Issue by tomrmyers** [wbreeze/iaccdb#162]
On Sat, Feb 15, 2020 at 11:44 AM Weston Liu <weston.liu@charter.net> wrote:
Hello!

Mark Budd Sr. and Mark Budd Jr. are attending a Judges School this
weekend.   Jr reports that he has volunteered to Assistant Judge but
when I look at the IAC DB for his Assistant Judge record I see two
entries and one reports an error.   We think that his most recent
volunteer work is behind that error.  Could we get this record fixed up?

In addition, I tried to look both of them up by going to various
versions of https://www.iac.org/users/mark-budd-jr, -st, etc and have
not successfully guessed what the URL for their info is. Could you help
me out with this?

Thanks for the help!

Wes

**Comment by djmolny** [comment]
Wes, you can look up member names at: https://www.iac.org/user-list (requires Editor permissions, which you have).

I'm taking a first look into the data error tonight. Even if a fix presents itself, I'll want to coordinate with Doug L since I'm new to the IACCDB fix & release process.

**Comment by djmolny** [comment]
The error arises in line 27 of `app/controllers/assistants_controller.rb`:
`      fys = flights.sort_by { |flight| flight.category.sequence }`

The problem is that there's a many-to-many relationship between the Flight and Category, introduced with commit #4e66112fb. Thus `flight.categories` is a legitimate method, but `flight.category` is not.

My proposed fix is to add the following code to `app/models/flight.rb`:

```def category
    categories.first
end```

**Comment by tomrmyers** [comment]
Hi DJ,

Great job, thank you. I have also tried to contact Doug. Hopefully he will
reply. If not, then go for it.

Thanx very much,
Tom.

**Comment by tomrmyers** [comment]
I'm in contact with Doug.

I've bench tested the fix. Just need to close the loop with Doug on how
to formally test & deploy.
