### ISSUE TITLE
Display IAC# on pages for individual pilots, judges, and assistants

### ISSUE THREAD

**Issue by djmolny** [wbreeze/iaccdb#70]
Periodically we have to troubleshoot the data, and/or correlate records with those on the IAC web site.

Since IAC number is our unique member identifier, it would be helpful to see it displayed on the IACCDB pages that pertain to a single individual (pilots, judges, assistants).

**Comment by wbreeze** [comment]
I've always treated IAC number as privileged information, like your SSN, driver's license ID, or pilot certificate number. That's why you don't see it. I'm not sure who would be an authority for that. Perhaps group consensus from the exploder. How do you feel about showing your IAC number on IACCDB? Or, is it already readily visible, searchable or accessible elsewhere?
